services:
  - type: web
    name: jat-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate
    startCommand: gunicorn django_be.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_be.settings
      - key: PYTHONUNBUFFERED
        value: 1
    plan: free
    autoDeploy: true
    rootDir: .
