# Generated by Django 5.2.4 on 2025-07-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_application_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='application',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='application',
            name='job_url',
        ),
        migrations.RemoveField(
            model_name='application',
            name='notes',
        ),
    ]
